=== dashatretyakk/Lab2-OOP/src/main/resources/military_planes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="modelType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="countryType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="planeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="support"/>
            <xs:enumeration value="escort"/>
            <xs:enumeration value="fighter"/>
            <xs:enumeration value="interceptor"/>
            <xs:enumeration value="reconnaissance"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="seatNumberType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="booleanType">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>

    <xs:simpleType name="missileNumberType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dimensionType">
        <xs:restriction base="xs:decimal"/>
    </xs:simpleType>

    <xs:simpleType name="currencyType">
        <xs:restriction base="xs:decimal"/>
    </xs:simpleType>

    <xs:complexType name="charsType">
        <xs:sequence>
            <xs:element name="type" type="planeType"/>
            <xs:element name="seats" type="seatNumberType"/>
            <xs:element name="ammunition" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="missiles" type="missileNumberType"/>
                        <xs:element name="radar" type="booleanType"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="parametersType">
        <xs:sequence>
            <xs:element name="length" type="dimensionType">
                <xs:annotation>
                    <xs:documentation>Length in meters</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="width" type="dimensionType">
                <xs:annotation>
                    <xs:documentation>Width in meters</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="height" type="dimensionType">
                <xs:annotation>
                    <xs:documentation>Height in meters</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="planeComplexType">
        <xs:sequence>
            <xs:element name="model" type="modelType"/>
            <xs:element name="origin" type="countryType"/>
            <xs:element name="chars" type="charsType"/>
            <xs:element name="parameters" type="parametersType"/>
            <xs:element name="price" type="currencyType">
                <xs:annotation>
                    <xs:documentation>Price in talers</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:element name="planes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="plane" type="planeComplexType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== dashatretyakk/Lab2-OOP/src/main/resources/military_planes.xml
<?xml version="1.0" encoding="UTF-8"?>
<planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="military_planes.xsd">
    <plane id="p1">
        <model>F-22 Raptor</model>
        <origin>USA</origin>
        <chars>
            <type>fighter</type>
            <seats>1</seats>
            <ammunition>
                <missiles>8</missiles>
                <radar>true</radar>
            </ammunition>
        </chars>
        <parameters>
            <length>18.92</length>
            <width>13.56</width>
            <height>5.08</height>
        </parameters>
        <price>150000000</price>
    </plane>
    <plane id="p2">
        <model>F-35 Lightning II</model>
        <origin>USA</origin>
        <chars>
            <type>interceptor</type>
            <seats>1</seats>
            <ammunition>
                <missiles>6</missiles>
                <radar>true</radar>
            </ammunition>
        </chars>
        <parameters>
            <length>20.1</length>
            <width>14.1</width>
            <height>4.74</height>
        </parameters>
        <price>100000000</price>
    </plane>
    <plane id="p3">
        <model>F-16 Fighting Falcon</model>
        <origin>USA</origin>
        <chars>
            <type>fighter</type>
            <seats>1</seats>
            <ammunition>
                <missiles>6</missiles>
                <radar>true</radar>
            </ammunition>
        </chars>
        <parameters>
            <length>15.06</length>
            <width>9.96</width>
            <height>4.88</height>
        </parameters>
        <price>80000000</price>
    </plane>
    <plane id="p4">
        <model>F-15 Eagle</model>
        <origin>USA</origin>
        <chars>
            <type>fighter</type>
            <seats>1</seats>
            <ammunition>
                <missiles>8</missiles>
                <radar>true</radar>
            </ammunition>
        </chars>
        <parameters>
            <length>19.43</length>
            <width>13.05</width>
            <height>5.63</height>
        </parameters>
        <price>120000000</price>
    </plane>
    <plane id="p5">
        <model>Mirage 2000</model>
        <origin>France</origin>
        <chars>
            <type>interceptor</type>
            <seats>1</seats>
            <ammunition>
                <missiles>4</missiles>
                <radar>false</radar>
            </ammunition>
        </chars>
        <parameters>
            <length>14.36</length>
            <width>9.13</width>
            <height>5.20</height>
        </parameters>
        <price>70000000</price>
    </plane>
    <plane id="p6">
        <model>Gripen</model>
        <origin>Sweden</origin>
        <chars>
            <type>fighter</type>
            <seats>1</seats>
            <ammunition>
                <missiles>6</missiles>
                <radar>true</radar>
            </ammunition>
        </chars>
        <parameters>
            <length>14.10</length>
            <width>8.40</width>
            <height>4.50</height>
        </parameters>
        <price>60000000</price>
    </plane>
    <plane id="p7">
        <model>F/A-18 Hornet</model>
        <origin>USA</origin>
        <chars>
            <type>fighter</type>
            <seats>1</seats>
            <ammunition>
                <missiles>6</missiles>
                <radar>true</radar>
            </ammunition>
        </chars>
        <parameters>
            <length>17.07</length>
            <width>12.31</width>
            <height>4.66</height>
        </parameters>
        <price>94000000</price>
    </plane>
    <plane id="p8">
        <model>Typhoon FGR4</model>
        <origin>UK</origin>
        <chars>
            <type>fighter</type>
            <seats>1</seats>
            <ammunition>
                <missiles>8</missiles>
                <radar>true</radar>
            </ammunition>
        </chars>
        <parameters>
            <length>15.96</length>
            <width>11.09</width>
            <height>5.28</height>
        </parameters>
        <price>85000000</price>
    </plane>
    <plane id="p9">
        <model>SAAB JAS 39 Gripen</model>
        <origin>Sweden</origin>
        <chars>
            <type>fighter</type>
            <seats>1</seats>
            <ammunition>
                <missiles>6</missiles>
                <radar>true</radar>
            </ammunition>
        </chars>
        <parameters>
            <length>14.1</length>
            <width>8.4</width>
            <height>4.5</height>
        </parameters>
        <price>65000000</price>
    </plane>
    <plane id="p10">
        <model>Dassault Rafale</model>
        <origin>France</origin>
        <chars>
            <type>interceptor</type>
            <seats>1</seats>
            <ammunition>
                <missiles>9</missiles>
                <radar>true</radar>
            </ammunition>
        </chars>
        <parameters>
            <length>15.30</length>
            <width>10.90</width>
            <height>5.34</height>
        </parameters>
        <price>74000000</price>
    </plane>
</planes>
